### ISSUE TITLE
Test that native module encryption and decryption works

### ISSUE THREAD

**Issue by egrimley-arm** [veracruz-project/veracruz#502]
Currently there does not seem to be anything to test that the encryption and decryption implemented in `native_modules/aes.rs` and `native_modules/aead.rs` works, for example that encryption followed by decryption gives the original data.

(I added something like `output[1] = 3;` and nothing broke. Was I just lucky?)

**Comment by gbryant-arm** [comment]
Static native modules can easily be added to the tests, just need to add a line to the policy like this:
https://github.com/veracruz-project/veracruz/blob/0b80b58474eed04f077aff3dbb6a1414f63ebfbc/workspaces/shared.mk#L231-L239.
Testing dynamic native modules is a bit trickier right now since you need to inject the binaries and [native module sandboxer] in the exec environment. This should definitely be covered by the CI at some point, at least VOD.

As a side note the iotex branch of VOD contains a very similar piece of code to perform video encryption/decryption (cf. https://github.com/veracruz-project/video-object-detection/blob/iotex-demo/aes-ctr-enc-dec/src/main.rs and https://github.com/veracruz-project/video-object-detection/blob/iotex-demo/src/main.cpp), and that branch isn't part of the CI, only the main one is

**Comment by dreemkiller** [comment]
@egrimley-arm Is this complete?

**Comment by egrimley-arm** [comment]
I'm looking at this ...
